[tools]
flutter = "3.35.3"
rust = "1.89.0"
ruby = { version = "3.4.4", os = ["macos"] }
"npm:serve" = "14.2.5"
"npm:firebase-tools" = "14.17.0"
"cargo:flutter_rust_bridge_codegen" = "2.11.1"

[tasks."server:run"]
description = "Start the WebSocket server"
run = "cargo run"
dir = "server"
env = { RUST_LOG = "info", RUST_BACKTRACE = "1", PORT = "8080", HOST = "localhost" }

[tasks."generate"]
description = "Generate the Flutter Rust Bridge bindings"
run = "flutter_rust_bridge_codegen generate"

[tasks."dev:build"]
description = "Run the Flutter build runner"
run = "dart run build_runner build -d"

[tasks."dev:watch"]
description = "Run the Flutter build runner in watch mode"
run = "dart run build_runner watch -d"

[tasks."web:serve"]
description = "Serve the client build"
run = "serve build/web -c serve.json"

[tasks."web:deploy"]
description = "Deploy the Flutter web app to Firebase Hosting"
run = "firebase deploy --only hosting"

[tasks."web:build"]
description = "Build the Flutter web app"
run = "flutter_rust_bridge_codegen build-web"

[tasks."web:build-release"]
description = "Build the Flutter web app"
run = [
    "flutter_rust_bridge_codegen build-web --release",
    "flutter build web --wasm --release",
]
