// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:kunlabori/src/rust/frb_generated.dart';

part 'document.freezed.dart';

@freezed
sealed class SimpleDelta with _$SimpleDelta {
  const SimpleDelta._();

  const factory SimpleDelta.insert({required String text}) = SimpleDelta_Insert;
  const factory SimpleDelta.delete({required int deleteCount}) =
      SimpleDelta_Delete;
  const factory SimpleDelta.retain({required int retainCount}) =
      SimpleDelta_Retain;
}
