[package]
name = "rust_lib_kunlabori"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
automerge = "0.6.1"
flutter_rust_bridge = "=2.11.1"
log = "0.4.28"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }

[features]
default = ["log"]
log = []
