// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'model.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `to_api_error`

Stream<Partial> create({required String id, required bool existsOk}) =>
    RustLib.instance.api.crateApiInterfaceCreate(id: id, existsOk: existsOk);

void destroy({required String id}) =>
    RustLib.instance.api.crateApiInterfaceDestroy(id: id);

void insert({
  required String id,
  required int position,
  required String text,
}) => RustLib.instance.api.crateApiInterfaceInsert(
  id: id,
  position: position,
  text: text,
);

void delete({
  required String id,
  required int position,
  required int deleteCount,
}) => RustLib.instance.api.crateApiInterfaceDelete(
  id: id,
  position: position,
  deleteCount: deleteCount,
);

void merge({required String id, required List<int> update}) =>
    RustLib.instance.api.crateApiInterfaceMerge(id: id, update: update);

Uint8List stateVector({required String id}) =>
    RustLib.instance.api.crateApiInterfaceStateVector(id: id);

Uint8List diff({required String id, required List<int> since}) =>
    RustLib.instance.api.crateApiInterfaceDiff(id: id, since: since);

void undo({required String id}) =>
    RustLib.instance.api.crateApiInterfaceUndo(id: id);

void redo({required String id}) =>
    RustLib.instance.api.crateApiInterfaceRedo(id: id);

void setSelection({required String id, required int start, required int end}) =>
    RustLib.instance.api.crateApiInterfaceSetSelection(
      id: id,
      start: start,
      end: end,
    );

(int?, int?) selection({required String id}) =>
    RustLib.instance.api.crateApiInterfaceSelection(id: id);
