// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String greet({required String name}) =>
    RustLib.instance.api.crateApiInterfaceGreet(name: name);

Stream<String> create({required String id}) =>
    RustLib.instance.api.crateApiInterfaceCreate(id: id);

void insert({
  required String id,
  required int position,
  required String text,
}) => RustLib.instance.api.crateApiInterfaceInsert(
  id: id,
  position: position,
  text: text,
);

void delete({
  required String id,
  required int position,
  required int deleteCount,
}) => RustLib.instance.api.crateApiInterfaceDelete(
  id: id,
  position: position,
  deleteCount: deleteCount,
);
