// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String greet({required String name}) =>
    RustLib.instance.api.crateApiInterfaceGreet(name: name);

Stream<String> createDocument({required String id}) =>
    RustLib.instance.api.crateApiInterfaceCreateDocument(id: id);

void editDocument({
  required String id,
  required BigInt position,
  required PlatformInt64 deleteCount,
  required String text,
}) => RustLib.instance.api.crateApiInterfaceEditDocument(
  id: id,
  position: position,
  deleteCount: deleteCount,
  text: text,
);
