// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:kunlabori/src/rust/frb_generated.dart';

part 'model.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

@freezed
sealed class Partial with _$Partial {
  const Partial._();

  const factory Partial.delta(
    SimpleDelta field0,
  ) = Partial_Delta;
  const factory Partial.text(
    String field0,
  ) = Partial_Text;
  const factory Partial.update(
    Uint8List field0,
  ) = Partial_Update;
}

@freezed
sealed class SimpleDelta with _$SimpleDelta {
  const SimpleDelta._();

  const factory SimpleDelta.insert({
    required String text,
    required bool remote,
  }) = SimpleDelta_Insert;
  const factory SimpleDelta.delete({
    required int count,
    required bool remote,
  }) = SimpleDelta_Delete;
  const factory SimpleDelta.retain({
    required int count,
    required bool remote,
  }) = SimpleDelta_Retain;
}
